export const projects = [
  {
    slug: "apokon-residence",
    name: "Apokon Residence",
    client: "Lim Family",
    location: "Apokon, Tagum City",
    phase: "Construction",
    foreman: "Jun Alvarado",
    siteEngineer: "Engr. Mina Torres",
    architect: "Ar. Denise Mercado",
    crew: 18,
    budget: "PHP 8.4M",
    spent: "PHP 5.6M",
    progress: 68,
    due: "Jul 18",
    status: "On track",
    nextMilestone: "Roof framing inspection",
    risk: "Medium",
  },
  {
    slug: "tagum-clinic-fit-out",
    name: "Tagum Clinic Fit-Out",
    client: "DavaoCare",
    location: "Tagum City",
    phase: "Interior Works",
    foreman: "Carlo Bentulan",
    siteEngineer: "Engr. Paolo Cruz",
    architect: "Ar. Lia Santos",
    crew: 11,
    budget: "PHP 3.1M",
    spent: "PHP 1.4M",
    progress: 42,
    due: "Aug 05",
    status: "Needs review",
    nextMilestone: "Ceiling and MEP coordination",
    risk: "High",
  },
  {
    slug: "mawab-farm-villas",
    name: "Mawab Farm Villas",
    client: "North Ridge Dev.",
    location: "Mawab",
    phase: "Design Development",
    foreman: "Site pending",
    siteEngineer: "For assignment",
    architect: "Ar. Kian Dela Cruz",
    crew: 6,
    budget: "PHP 14.7M",
    spent: "PHP 0.9M",
    progress: 25,
    due: "Sep 12",
    status: "Planning",
    nextMilestone: "Client material approval",
    risk: "Low",
  },
  {
    slug: "panabo-office-annex",
    name: "Panabo Office Annex",
    client: "Greenline Corp.",
    location: "Panabo City",
    phase: "Turnover",
    foreman: "Ramil Soco",
    siteEngineer: "Engr. Jan Flores",
    architect: "Ar. Denise Mercado",
    crew: 9,
    budget: "PHP 5.8M",
    spent: "PHP 5.1M",
    progress: 91,
    due: "Jun 28",
    status: "Punch list",
    nextMilestone: "Final client walkthrough",
    risk: "Low",
  },
];

export const manpower = [
  {
    trade: "Masonry",
    total: 21,
    deployed: 19,
    standby: 2,
    lead: "Toto Amante",
    projects: "3 projects",
  },
  {
    trade: "Electrical",
    total: 8,
    deployed: 8,
    standby: 0,
    lead: "Rex Manalo",
    projects: "2 projects",
  },
  {
    trade: "Carpentry",
    total: 14,
    deployed: 12,
    standby: 2,
    lead: "Bong Sarmiento",
    projects: "4 projects",
  },
  {
    trade: "Painting",
    total: 10,
    deployed: 6,
    standby: 4,
    lead: "Allan Baarde",
    projects: "2 projects",
  },
];

export const contractItems = [
  ["Progress Billing 03", "Apokon Residence", "PHP 1.2M", "For approval"],
  ["Change Order 07", "Tagum Clinic Fit-Out", "PHP 214K", "Client review"],
  ["Supplier PO", "Mawab Farm Villas", "PHP 680K", "Drafting"],
  ["Retention Release", "Panabo Office Annex", "PHP 290K", "Accounting"],
];

export const serviceRequests = [
  ["Structural revision", "Apokon Residence", "Architect review", "Today"],
  ["Tile procurement", "Tagum Clinic Fit-Out", "Purchasing", "Tomorrow"],
  ["Mobilization permit", "Mawab Farm Villas", "Admin", "Jun 07"],
  ["Final billing packet", "Panabo Office Annex", "Accounting", "Jun 12"],
  ["Client finish board", "Tagum Clinic Fit-Out", "Interior team", "Jun 14"],
];

export const schedule = [
  ["08:00", "Toolbox meeting", "Apokon Residence"],
  ["10:30", "MEP coordination", "Tagum Clinic Fit-Out"],
  ["13:00", "Supplier canvas review", "Main office"],
  ["15:30", "Punch list verification", "Panabo Office Annex"],
];
